In [21]:
import numpy as np
import scipy
import scipy.sparse as sparse
import matplotlib.pyplot as plt
import pandas as pd

# D4M (after you fix import path / editable install)
from D4M.assoc import Assoc
import D4M.util as util
from D4M.assoc import Assoc, readjson, val2col
import pandas as pd

print("Python:", __import__("sys").version.split()[0])
print("NumPy:", np.__version__)
print("SciPy:", scipy.__version__)
print("Sparse type:", type(sparse.coo_matrix(([], ([], [])), shape=(0, 0))).__name__)
print("D4M util:", util.__file__)

Python: 3.13.1
NumPy: 2.4.1
SciPy: 1.17.0
Sparse type: coo_matrix
D4M util: /Users/gcr/ingis.Wk/D4M.py/D4M/util.py

In [ ]:
import sys
print(sys.executable)
print(sys.path[:3])

/Users/gcr/ingis.Wk/D4M.py/.venv/bin/python
['/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python313.zip', '/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13', '/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload']

NameError: name 'AA' is not defined

In [6]:
PATH = "/Users/gcr/ingis.Wk/FHIRSDS/aa-bundles"
AA1 = readjson(PATH + "/Adam631_Buckridge80_2f3fd555-23e0-adae-ccb8-438dca7e7304.json")
AA2 = readjson(PATH + "/Agatha2_Reichert620_5fd77197-1344-4b48-1907-712e228ce790.json")
AA3 = readjson(PATH + "/Akilah516_Jenkins714_946e334e-0ca7-71d8-df09-edbe34d162c0.json")
AA4 = readjson(PATH + "/Alicia629_Ariadna374_Flores439_c8fac0d1-a829-cad1-9fc9-18ae6d7e8f9d.json")

In [7]:
AA = AA1 + AA2 + AA3 + AA4

In [8]:
Assoc.size(AA)

(2634, 3879)

In [9]:
Encounter = AA[util.startswith("Encounter,"), :]

In [10]:
Encounter.get_row()

array(['Encounter/00039ac4-4cc7-d998-8f5c-905d9d2a351a',
       'Encounter/01187c15-bb56-037a-11d7-48a91e89156f',
       'Encounter/08a89c96-a8a4-9231-0548-6bec81b95404',
       'Encounter/0a822120-d8f6-ac05-45d3-75fc9884df5d',
       'Encounter/0cf1035f-417d-373e-b28c-be5772c66494',
       'Encounter/0e3af9e5-53ba-937e-3d69-eecd80d8c672',
       'Encounter/0e42a8cb-8cb1-340d-f8c9-eb97be051475',
       'Encounter/0eae3eb1-29fa-e89d-48cd-7495a8403acc',
       'Encounter/11ffef56-bbfb-2dad-d3bd-04ad7dd49164',
       'Encounter/1494a238-2ba0-79cc-bae6-6a8b5b2eb2a6',
       'Encounter/165f3aa9-01b6-3597-ed55-c29b4c11a4ff',
       'Encounter/16764e02-0ff3-7ba4-11e9-8ce45fa7e7c5',
       'Encounter/188384c4-6559-a45b-b092-92833b446d4f',
       'Encounter/1a0fbd13-3563-dd3d-5248-1d27e9fa496b',
       'Encounter/1a7cb9a4-fe2c-271c-8674-b4e9971df129',
       'Encounter/1c5fa82f-e2ed-6038-1fa9-ee7218ec38a4',
       'Encounter/1d4a2c75-2b54-e1c0-c404-f957cc005528',
       'Encounter/1d916182-7789-01fe-84eb-e3b910c1a6ca',
       'Encounter/1ed787d5-4fa5-c61f-5231-6be9aa01a438',
       'Encounter/22b3797c-7efc-81dd-fa69-9d17f0546be6',
       'Encounter/268b0a59-28dc-a373-6954-2f7e595d1afb',
       'Encounter/288a530b-da25-06f7-5bed-ed44396d2336',
       'Encounter/29b2a733-3153-434e-a963-024b6ac9530f',
       'Encounter/2a311985-3532-05f3-c043-9a745bd10f72',
       'Encounter/2a5dae2e-ef93-06e0-f2c7-55b4dbcd2d81',
       'Encounter/2b4b1ef7-7c80-cd1d-3dd3-34b696bd8bae',
       'Encounter/2ee59ca5-9985-84ed-1ed2-6d75f8420b74',
       'Encounter/2ff605b5-cf65-47cc-e3b0-6b3ba7fc6412',
       'Encounter/313730ea-2834-019f-ebc2-dbfe4f1879db',
       'Encounter/3138c793-1cbe-1759-2b21-d7fa762978e3',
       'Encounter/32de7f9e-73e4-113f-8cdb-1a5611822ea2',
       'Encounter/36ce3f3e-bd99-3ab9-d722-9841c2c3fa30',
       'Encounter/375a0290-ad2c-12d2-5c88-a98d939e6113',
       'Encounter/3aef1eb5-634f-2b2d-cd29-145ed6a97e0e',
       'Encounter/3c66aa19-7273-8216-836e-c87bc29654b3',
       'Encounter/3c6fe44a-f450-c749-4869-919c072dce83',
       'Encounter/3e57dbc7-c9b3-d9f0-6419-706b49e7dc9d',
       'Encounter/40d38072-a5ff-dc89-8d7a-12c27883a15d',
       'Encounter/45cadcf4-fc8d-8578-d6d9-460d9751a3dc',
       'Encounter/45d81db9-6001-b17b-cde0-cd63361b4a20',
       'Encounter/4786acf1-d8d7-7bea-6e64-0cd536d91864',
       'Encounter/48efcd5f-46dd-a259-4d3b-1ac87c23629d',
       'Encounter/49f45068-ce49-759f-b130-a69b90cface8',
       'Encounter/4a4b49a1-6d9e-0151-e72f-915a15135459',
       'Encounter/4b121d43-c81a-7061-e290-a22c4b395410',
       'Encounter/4b748ecc-ef08-34f9-0e18-d7638b3054cf',
       'Encounter/4d1b6fb5-c1d3-707c-581f-f86be7dcb7d1',
       'Encounter/4e6ca826-5f50-8a07-7e33-5301b88d7b75',
       'Encounter/5497cb8d-959f-1936-907b-f8fea852ba55',
       'Encounter/56404f13-d153-a274-090e-fd61a1be004e',
       'Encounter/564b7104-981d-884d-799e-10d86a3b5fe8',
       'Encounter/56a3c3dd-a5a6-2ae8-8caf-a489ebf62c01',
       'Encounter/5878bcf5-dde8-143e-e1a6-4a2bc3c69bd9',
       'Encounter/58985b4f-9942-28df-a0ac-09eadf1f2cf6',
       'Encounter/5c672513-cb3a-e97d-51f2-adc194fe9bd4',
       'Encounter/5c96de6e-ed45-a1e5-41db-72b8cc2b442f',
       'Encounter/5d267fe1-f80f-1cc5-aa30-cfcea71889ed',
       'Encounter/5d2da8b4-cda7-b72c-b87f-25820d6e8655',
       'Encounter/62f6a1cf-a030-00c8-3a06-03de0d187204',
       'Encounter/64d0d3a7-77fe-be3b-6621-97f2e594e4f2',
       'Encounter/65be2a7d-69c3-3763-ab19-4b840d6cf7e1',
       'Encounter/66029651-6ad9-43f3-912f-5331767f50f0',
       'Encounter/67866dfb-e57e-c4ae-0459-6530d96d266e',
       'Encounter/67c254bc-851a-2c40-ebef-4aa3f1817f7c',
       'Encounter/688f1fc1-53c2-d727-6a9f-8f1b3415a0b8',
       'Encounter/6b4491eb-0fe4-3049-ea96-9ea8f0f07927',
       'Encounter/6dd31aa2-2d80-7bc1-dc34-b7d034309944',
       'Encounter/6f7c7e6e-348c-e28a-cd83-8e6f060d0e61',
       'Encounter/70b6cc28-9a18-50f4-ceb8-fbc70542bf07',
       'Encounter/71b5498a-024d-e289-bde1-b9d7915ee798',
       'Encounter/7251cf8c-e95e-d5ef-44b6-9fa74511a5f7',
       'Encounter/75eaacf1-923c-d603-961e-f9c9951a8b06',
       'Encounter/7a528d5a-c27a-a3c1-7bd2-a11eb9bb0854',
       'Encounter/7f46a0d3-a847-851d-bb95-4e66cc881c88',
       'Encounter/8079e29b-c330-b4f9-b49d-36101b0c2ed0',
       'Encounter/826ff4dd-c305-f1d3-4221-459bda927ffd',
       'Encounter/868b1d02-b46c-1488-4d20-922fb8101f70',
       'Encounter/8b4183b4-6119-cc9f-19c4-2dd8e82522a6',
       'Encounter/8d178f38-ed54-7344-ec5a-fdd16560901b',
       'Encounter/91425808-52b3-9f06-6a68-bab5bf462ff3',
       'Encounter/99bbe17d-e9e1-c6c0-627a-d6867fde26c3',
       'Encounter/9c8a188a-7ff1-566b-7d36-f2e14aa6c1e8',
       'Encounter/9dd1d69b-b128-1e5c-83b8-8e954b5c5d42',
       'Encounter/9e45c28f-d880-7e6d-1546-9f1a2b904017',
       'Encounter/9fcb6714-7f9b-b31b-a0c1-be9ee183f39c',
       'Encounter/a143538b-0ae7-c4cf-99fa-4560dd2689a6',
       'Encounter/a1cdc168-69da-a495-eacb-1d83f722ce4e',
       'Encounter/a27e9643-6690-9885-ae7b-2cbf8ca49fb5',
       'Encounter/a946a458-2b2b-1700-a486-ebb4847172c8',
       'Encounter/aa1343ca-2869-05d1-e674-8624c18c1d9f',
       'Encounter/ab8932b8-9556-b353-8f7c-f978f10756c4',
       'Encounter/ac594fa0-4c76-2caf-c086-76b1c690bc5c',
       'Encounter/aeada0bd-7fd4-19a0-aea8-d4560c2f095e',
       'Encounter/b259a20c-6cea-66d3-e1e4-db618d2536d2',
       'Encounter/b39ff583-f3b3-a851-8906-24433a6d60c8',
       'Encounter/b3ac00e9-97dd-4798-b474-aa0cf4102512',
       'Encounter/b3eece09-0330-ddc8-84b9-9b33c30d00f3',
       'Encounter/b4c52544-9bd2-750a-21a1-21cd22204bf1',
       'Encounter/b592f6ed-ac06-a01c-619f-89a37cfa4d30',
       'Encounter/b81b51bf-cd9c-7b73-2db4-888d9731f1ad',
       'Encounter/b863a251-21f4-5471-daaa-ef0f6d46ddd9',
       'Encounter/b89b7fd5-6079-bab8-5b4d-18450c40cefb',
       'Encounter/b8ccd0f8-d802-eda0-3b62-a4afbfd62840',
       'Encounter/bb47d4a7-a92d-377c-fa50-a7916082e34c',
       'Encounter/bb65619f-15aa-2626-787e-cdf9358a7cd6',
       'Encounter/bc02916f-c92a-e77a-3cf7-728557439b2a',
       'Encounter/bcef312e-c278-7e8a-240f-c115d341c5ff',
       'Encounter/bcf4dc8e-1160-9bd1-963a-39503fab63fe',
       'Encounter/bfa19373-8141-12be-3881-532226a77eed',
       'Encounter/c4fd93d5-1cbe-2e2f-c7b7-d8617ec8c982',
       'Encounter/c76848e1-9c78-ba5d-5800-9dcf5ab9be96',
       'Encounter/c82c6c71-f2da-81a6-d74a-02c08578b0a3',
       'Encounter/c85c9047-8a9c-8723-4901-ddc183e98ee6',
       'Encounter/c909d126-ce86-9568-751e-342ef785dde5',
       'Encounter/c984e880-d10a-0e66-2e85-11b08e318a80',
       'Encounter/ca30c4da-c7c3-e16f-6787-604f3eabe2ba',
       'Encounter/cb04e4c4-32c8-5a42-af44-41aaf98a39f5',
       'Encounter/cbdc77bc-bf7d-2ed8-dd54-75be430fb58c',
       'Encounter/cc17bb6b-3fde-c6ee-126d-b720cea3c591',
       'Encounter/cd4b81c8-6d3c-01bd-7160-d5cdd3ff58e4',
       'Encounter/d11f3e50-503b-b6dd-33bc-013713d5321b',
       'Encounter/d488a6b8-eb21-df5f-107d-81d54e519843',
       'Encounter/d7ef84ae-1ca3-9a0a-3f64-53364e621bb7',
       'Encounter/d9c9329f-105c-afe7-f533-414639939550',
       'Encounter/d9cb41f8-24a2-61af-c69f-4a52391be12d',
       'Encounter/d9f78254-9a3f-4d60-9d31-2969dfc48c47',
       'Encounter/dac4ae6f-3d5d-d227-42cb-103f0a02db80',
       'Encounter/dbf5789a-2de7-8e2e-67d8-5bc3f365099e',
       'Encounter/dbffe2d7-e17b-d187-db78-80e01097f61e',
       'Encounter/df695e1d-66e6-01d7-588a-945c9f3a8ba0',
       'Encounter/df8da1c2-a7f7-4a95-e675-7fee6b283bf0',
       'Encounter/e084ac7a-e47b-5139-5db6-25dad1c2079f',
       'Encounter/e103114f-2455-d372-2d31-7c75031365ab',
       'Encounter/e13e748f-e2d2-726a-4c07-2c9e47215eeb',
       'Encounter/e2d22c79-9c94-6bb5-6d34-063d1593fbaa',
       'Encounter/e4eba79b-36bc-3f74-abd7-a423821e43dc',
       'Encounter/e7934cbd-1fa2-e5a5-eed6-94ffd780f4aa',
       'Encounter/e9433cb7-1de6-6e40-c6ba-f3cfc9f0ae2f',
       'Encounter/ec364921-66c2-7ac5-c308-629dda439a94',
       'Encounter/ec4e9a2f-481f-09e9-7365-2a1e86da0b44',
       'Encounter/f2f0d5df-c3c2-b537-7640-3b04aa9fc1bb',
       'Encounter/f526acee-4330-2679-2a33-4ebe34b9c5b9',
       'Encounter/f72eff22-eea6-35a2-17db-29444c52ccdd',
       'Encounter/fa04845b-b9fd-b059-5642-fd6b8f9bc9f6',
       'Encounter/fb0f4155-aa94-9738-234c-1939105d9e36',
       'Encounter/fcec63ed-8671-e619-4722-cc8e1c6a0b28',
       'Encounter/fd225927-03dc-622f-1b20-6bf3451a04a3'], dtype='<U61')

In [11]:
Assoc.nnz(AA)

np.int64(98851)

In [12]:
Start = AA[:, util.startswith("Encounter.period.start,")]

In [14]:
End = AA[:, util.startswith("Encounter.period.end,")]

In [28]:
found = (Start + End).find() 

# Case A: find() returns a tuple/list of 3 arrays: (rows, cols, vals)
if isinstance(found, (tuple, list)) and len(found) == 3 and not isinstance(found[0], (tuple, list)) and hasattr(found[0], "__len__"):
    rows, cols, vals = found
    df = pd.DataFrame({"row": rows, "col": cols, "val": vals})

# Case B: find() returns an (N x 3) iterable of triples
else:
    df = pd.DataFrame(list(found), columns=["row", "col", "val"])

df.head()

,row,col,val
0,Encounter/00039ac4-4cc7-d998-8f5c-905d9d2a351a,Encounter.period.start,2017-06-24T10:19:32-04:00
1,Encounter/01187c15-bb56-037a-11d7-48a91e89156f,Encounter.period.start,1985-12-05T09:20:44-05:00
2,Encounter/08a89c96-a8a4-9231-0548-6bec81b95404,Encounter.period.start,2019-09-20T17:35:25-04:00
3,Encounter/0a822120-d8f6-ac05-45d3-75fc9884df5d,Encounter.period.start,1982-12-23T09:20:44-05:00
4,Encounter/0cf1035f-417d-373e-b28c-be5772c66494,Encounter.period.start,1958-05-01T10:20:44-04:00

In [29]:
enc = df[
    df["row"].astype(str).str.startswith("Encounter/") &
    df["col"].isin(["Encounter.period.start", "Encounter.period.end"])
]

wide = enc.pivot_table(index="row", columns="col", values="val", aggfunc="first")

wide["start_dt"] = pd.to_datetime(wide["Encounter.period.start"], utc=True, errors="coerce")
wide["end_dt"]   = pd.to_datetime(wide["Encounter.period.end"],   utc=True, errors="coerce")

wide["duration_minutes"] = (wide["end_dt"] - wide["start_dt"]).dt.total_seconds() / 60

wide[["start_dt", "end_dt", "duration_minutes"]].head()

col,start_dt,end_dt,duration_minutes
row,,,
Encounter/00039ac4-4cc7-d998-8f5c-905d9d2a351a,2017-06-24 14:19:32+00:00,2017-06-24 14:34:32+00:00,15.000000
Encounter/01187c15-bb56-037a-11d7-48a91e89156f,1985-12-05 14:20:44+00:00,1985-12-05 15:16:24+00:00,55.666667
Encounter/08a89c96-a8a4-9231-0548-6bec81b95404,2019-09-20 21:35:25+00:00,2019-09-20 21:50:25+00:00,15.000000
Encounter/0a822120-d8f6-ac05-45d3-75fc9884df5d,1982-12-23 14:20:44+00:00,1982-12-23 14:35:44+00:00,15.000000
Encounter/0cf1035f-417d-373e-b28c-be5772c66494,1958-05-01 14:20:44+00:00,1958-05-01 15:16:48+00:00,56.066667

In [30]:
wide[wide["duration_minutes"] > 30]

col,Encounter.period.end,Encounter.period.start,start_dt,end_dt,duration_minutes
row,,,,,
Encounter/01187c15-bb56-037a-11d7-48a91e89156f,1985-12-05T10:16:24-05:00,1985-12-05T09:20:44-05:00,1985-12-05 14:20:44+00:00,1985-12-05 15:16:24+00:00,55.666667
Encounter/0cf1035f-417d-373e-b28c-be5772c66494,1958-05-01T11:16:48-04:00,1958-05-01T10:20:44-04:00,1958-05-01 14:20:44+00:00,1958-05-01 15:16:48+00:00,56.066667
Encounter/0e3af9e5-53ba-937e-3d69-eecd80d8c672,1978-06-01T10:51:10-04:00,1978-06-01T10:20:44-04:00,1978-06-01 14:20:44+00:00,1978-06-01 14:51:10+00:00,30.433333
Encounter/1a7cb9a4-fe2c-271c-8674-b4e9971df129,1977-03-02T18:02:48-05:00,1977-03-02T17:23:00-05:00,1977-03-02 22:23:00+00:00,1977-03-02 23:02:48+00:00,39.800000
Encounter/22b3797c-7efc-81dd-fa69-9d17f0546be6,2016-05-19T13:01:53-04:00,2016-05-19T10:03:15-04:00,2016-05-19 14:03:15+00:00,2016-05-19 17:01:53+00:00,178.633333
Encounter/268b0a59-28dc-a373-6954-2f7e595d1afb,1980-06-12T10:59:31-04:00,1980-06-12T10:20:44-04:00,1980-06-12 14:20:44+00:00,1980-06-12 14:59:31+00:00,38.783333
Encounter/288a530b-da25-06f7-5bed-ed44396d2336,1976-05-20T11:03:40-04:00,1976-05-20T10:20:44-04:00,1976-05-20 14:20:44+00:00,1976-05-20 15:03:40+00:00,42.933333
Encounter/29b2a733-3153-434e-a963-024b6ac9530f,2019-05-04T10:26:42-04:00,2019-05-04T07:19:32-04:00,2019-05-04 11:19:32+00:00,2019-05-04 14:26:42+00:00,187.166667
Encounter/2b4b1ef7-7c80-cd1d-3dd3-34b696bd8bae,2023-04-14T20:32:49-04:00,2023-04-14T17:35:25-04:00,2023-04-14 21:35:25+00:00,2023-04-15 00:32:49+00:00,177.400000
Encounter/2ff605b5-cf65-47cc-e3b0-6b3ba7fc6412,1974-05-09T11:10:08-04:00,1974-05-09T10:20:44-04:00,1974-05-09 14:20:44+00:00,1974-05-09 15:10:08+00:00,49.400000
Encounter/313730ea-2834-019f-ebc2-dbfe4f1879db,2021-05-27T11:08:49-04:00,2021-05-27T10:03:15-04:00,2021-05-27 14:03:15+00:00,2021-05-27 15:08:49+00:00,65.566667
Encounter/36ce3f3e-bd99-3ab9-d722-9841c2c3fa30,1985-07-18T11:20:44-04:00,1985-07-18T10:20:44-04:00,1985-07-18 14:20:44+00:00,1985-07-18 15:20:44+00:00,60.000000
Encounter/3aef1eb5-634f-2b2d-cd29-145ed6a97e0e,1977-06-09T16:22:01-04:00,1977-06-09T10:20:44-04:00,1977-06-09 14:20:44+00:00,1977-06-09 20:22:01+00:00,361.283333
Encounter/3e57dbc7-c9b3-d9f0-6419-706b49e7dc9d,1985-11-21T10:20:44-05:00,1985-11-21T09:20:44-05:00,1985-11-21 14:20:44+00:00,1985-11-21 15:20:44+00:00,60.000000
Encounter/4786acf1-d8d7-7bea-6e64-0cd536d91864,1985-12-19T12:22:44-05:00,1985-12-19T09:20:44-05:00,1985-12-19 14:20:44+00:00,1985-12-19 17:22:44+00:00,182.000000
Encounter/49f45068-ce49-759f-b130-a69b90cface8,1979-06-07T11:08:19-04:00,1979-06-07T10:20:44-04:00,1979-06-07 14:20:44+00:00,1979-06-07 15:08:19+00:00,47.583333
Encounter/4b748ecc-ef08-34f9-0e18-d7638b3054cf,1982-07-01T11:40:54-04:00,1982-07-01T10:20:44-04:00,1982-07-01 14:20:44+00:00,1982-07-01 15:40:54+00:00,80.166667
Encounter/56404f13-d153-a274-090e-fd61a1be004e,1949-06-16T11:20:18-04:00,1949-06-16T10:20:44-04:00,1949-06-16 14:20:44+00:00,1949-06-16 15:20:18+00:00,59.566667
Encounter/564b7104-981d-884d-799e-10d86a3b5fe8,2018-09-28T19:55:41-04:00,2018-09-28T17:35:25-04:00,2018-09-28 21:35:25+00:00,2018-09-28 23:55:41+00:00,140.266667
Encounter/56a3c3dd-a5a6-2ae8-8caf-a489ebf62c01,1981-06-18T11:02:53-04:00,1981-06-18T10:20:44-04:00,1981-06-18 14:20:44+00:00,1981-06-18 15:02:53+00:00,42.150000
Encounter/5878bcf5-dde8-143e-e1a6-4a2bc3c69bd9,1981-03-22T23:34:30-05:00,1981-03-22T23:00:37-05:00,1981-03-23 04:00:37+00:00,1981-03-23 04:34:30+00:00,33.883333
Encounter/5c96de6e-ed45-a1e5-41db-72b8cc2b442f,1980-04-02T22:09:14-05:00,1980-04-02T21:28:53-05:00,1980-04-03 02:28:53+00:00,1980-04-03 03:09:14+00:00,40.350000
Encounter/5d267fe1-f80f-1cc5-aa30-cfcea71889ed,1978-03-19T19:19:07-05:00,1978-03-19T18:42:44-05:00,1978-03-19 23:42:44+00:00,1978-03-20 00:19:07+00:00,36.383333
Encounter/62f6a1cf-a030-00c8-3a06-03de0d187204,1980-04-02T23:00:37-05:00,1980-04-02T22:29:11-05:00,1980-04-03 03:29:11+00:00,1980-04-03 04:00:37+00:00,31.433333
Encounter/64d0d3a7-77fe-be3b-6621-97f2e594e4f2,1982-03-21T01:04:31-05:00,1982-03-21T00:25:45-05:00,1982-03-21 05:25:45+00:00,1982-03-21 06:04:31+00:00,38.766667
Encounter/688f1fc1-53c2-d727-6a9f-8f1b3415a0b8,1936-05-28T11:02:50-04:00,1936-05-28T10:20:44-04:00,1936-05-28 14:20:44+00:00,1936-05-28 15:02:50+00:00,42.100000
Encounter/6dd31aa2-2d80-7bc1-dc34-b7d034309944,1986-07-17T10:58:41-04:00,1986-07-17T10:20:44-04:00,1986-07-17 14:20:44+00:00,1986-07-17 14:58:41+00:00,37.950000
Encounter/6f7c7e6e-348c-e28a-cd83-8e6f060d0e61,1983-04-28T11:00:31-04:00,1983-04-28T10:20:44-04:00,1983-04-28 14:20:44+00:00,1983-04-28 15:00:31+00:00,39.783333
Encounter/8079e29b-c330-b4f9-b49d-36101b0c2ed0,2018-05-17T10:52:44-04:00,2018-05-17T10:03:15-04:00,2018-05-17 14:03:15+00:00,2018-05-17 14:52:44+00:00,49.483333
Encounter/826ff4dd-c305-f1d3-4221-459bda927ffd,1983-07-14T13:14:00-04:00,1983-07-14T10:20:44-04:00,1983-07-14 14:20:44+00:00,1983-07-14 17:14:00+00:00,173.266667
Encounter/868b1d02-b46c-1488-4d20-922fb8101f70,2021-05-20T11:00:52-04:00,2021-05-20T10:03:15-04:00,2021-05-20 14:03:15+00:00,2021-05-20 15:00:52+00:00,57.616667
Encounter/9e45c28f-d880-7e6d-1546-9f1a2b904017,1984-03-30T11:26:39-05:00,1984-03-30T10:47:49-05:00,1984-03-30 15:47:49+00:00,1984-03-30 16:26:39+00:00,38.833333
Encounter/9fcb6714-7f9b-b31b-a0c1-be9ee183f39c,2017-05-11T10:48:55-04:00,2017-05-11T10:03:15-04:00,2017-05-11 14:03:15+00:00,2017-05-11 14:48:55+00:00,45.666667
Encounter/a1cdc168-69da-a495-eacb-1d83f722ce4e,2017-05-25T13:53:03-04:00,2017-05-25T10:03:15-04:00,2017-05-25 14:03:15+00:00,2017-05-25 17:53:03+00:00,229.800000
Encounter/a27e9643-6690-9885-ae7b-2cbf8ca49fb5,1985-07-11T10:54:25-04:00,1985-07-11T10:20:44-04:00,1985-07-11 14:20:44+00:00,1985-07-11 14:54:25+00:00,33.683333
Encounter/a946a458-2b2b-1700-a486-ebb4847172c8,1982-12-10T09:35:44-05:00,1982-11-18T09:20:44-05:00,1982-11-18 14:20:44+00:00,1982-12-10 14:35:44+00:00,31695.000000
Encounter/aa1343ca-2869-05d1-e674-8624c18c1d9f,1979-04-10T20:45:51-05:00,1979-04-10T20:03:44-05:00,1979-04-11 01:03:44+00:00,1979-04-11 01:45:51+00:00,42.116667
Encounter/aeada0bd-7fd4-19a0-aea8-d4560c2f095e,1984-07-05T11:12:34-04:00,1984-07-05T10:20:44-04:00,1984-07-05 14:20:44+00:00,1984-07-05 15:12:34+00:00,51.833333
Encounter/b592f6ed-ac06-a01c-619f-89a37cfa4d30,1970-06-13T08:59:36-04:00,1970-06-11T10:20:44-04:00,1970-06-11 14:20:44+00:00,1970-06-13 12:59:36+00:00,2798.866667
Encounter/b863a251-21f4-5471-daaa-ef0f6d46ddd9,1977-05-26T11:01:03-04:00,1977-05-26T10:20:44-04:00,1977-05-26 14:20:44+00:00,1977-05-26 15:01:03+00:00,40.316667
Encounter/bcf4dc8e-1160-9bd1-963a-39503fab63fe,1985-04-03T12:45:36-05:00,1985-04-03T12:10:49-05:00,1985-04-03 17:10:49+00:00,1985-04-03 17:45:36+00:00,34.783333
Encounter/c4fd93d5-1cbe-2e2f-c7b7-d8617ec8c982,1986-04-24T14:07:11-05:00,1986-04-24T13:36:44-05:00,1986-04-24 18:36:44+00:00,1986-04-24 19:07:11+00:00,30.450000
Encounter/c82c6c71-f2da-81a6-d74a-02c08578b0a3,1983-04-17T09:35:44-05:00,1983-04-07T09:20:44-05:00,1983-04-07 14:20:44+00:00,1983-04-17 14:35:44+00:00,14415.000000
Encounter/cbdc77bc-bf7d-2ed8-dd54-75be430fb58c,1982-06-24T11:05:10-04:00,1982-06-24T10:20:44-04:00,1982-06-24 14:20:44+00:00,1982-06-24 15:05:10+00:00,44.433333
Encounter/d11f3e50-503b-b6dd-33bc-013713d5321b,2024-04-19T20:37:44-04:00,2024-04-19T17:35:25-04:00,2024-04-19 21:35:25+00:00,2024-04-20 00:37:44+00:00,182.316667
Encounter/d9cb41f8-24a2-61af-c69f-4a52391be12d,1983-06-30T11:06:19-04:00,1983-06-30T10:20:44-04:00,1983-06-30 14:20:44+00:00,1983-06-30 15:06:19+00:00,45.583333
Encounter/dac4ae6f-3d5d-d227-42cb-103f0a02db80,2018-07-17T11:30:33-04:00,2018-07-17T10:30:33-04:00,2018-07-17 14:30:33+00:00,2018-07-17 15:30:33+00:00,60.000000
Encounter/df695e1d-66e6-01d7-588a-945c9f3a8ba0,2024-05-23T10:50:32-04:00,2024-05-23T10:03:15-04:00,2024-05-23 14:03:15+00:00,2024-05-23 14:50:32+00:00,47.283333
Encounter/e13e748f-e2d2-726a-4c07-2c9e47215eeb,1979-06-21T13:58:16-04:00,1979-06-21T10:20:44-04:00,1979-06-21 14:20:44+00:00,1979-06-21 17:58:16+00:00,217.533333
Encounter/e7934cbd-1fa2-e5a5-eed6-94ffd780f4aa,2024-05-25T10:54:55-04:00,2024-05-25T07:19:32-04:00,2024-05-25 11:19:32+00:00,2024-05-25 14:54:55+00:00,215.383333
Encounter/fa04845b-b9fd-b059-5642-fd6b8f9bc9f6,1985-07-25T12:57:34-04:00,1985-07-25T10:20:44-04:00,1985-07-25 14:20:44+00:00,1985-07-25 16:57:34+00:00,156.833333
Encounter/fd225927-03dc-622f-1b20-6bf3451a04a3,1987-02-16T06:47:56-05:00,1987-01-22T09:20:44-05:00,1987-01-22 14:20:44+00:00,1987-02-16 11:47:56+00:00,35847.200000